name: "Run TKG Tests"
on:
  issue_comment:
    types: [created]
jobs:
  testTKG:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, 'run tkg-test')
    steps:
      # get-pr step by @Simran-B https://github.com/actions/checkout/issues/331#issuecomment-707103442
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }} # or .head.ref for branch name
          path: 'testTKG'
      - name: Set up JDK
        uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Create success comment
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            comment_body = `
            @${{ github.actor }} TKG test build started, workflow Run ID: [${{ GITHUB.RUN_ID }}](${{ GITHUB.SERVER_URL }}/${{ GITHUB.REPOSITORY }}/actions/runs/${{ GITHUB.RUN_ID }})
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment_body
            })

      - name: parse options
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          echo "TKG_TEST_OPTIONS=`echo '${{ env.COMMENT_BODY }}' | sed 's/.*run tkg-test\(.*\)/\1/'`" >> $GITHUB_ENV

      - name: run script
        env:
          TEST_JDK_HOME: ${{ env.JAVA_HOME }}
          TEST_OPTIONS: ${{ env.TKG_TEST_OPTIONS }}
        run: |
          cd testTKG/TKG/scripts/testTKG
          python testRunner.py $TEST_OPTIONS

  reportFailure:
    runs-on: ubuntu-latest
    needs: [testTKG]
    if: failure()
    steps:
    - name: Create comment
      uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          comment_body = `
          @${{ github.actor }} Build(s) failed, workflow Run ID: [${{ GITHUB.RUN_ID }}](${{ GITHUB.SERVER_URL }}/${{ GITHUB.REPOSITORY }}/actions/runs/${{ GITHUB.RUN_ID }})
          `;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment_body
          })

  reportCancel:
    runs-on: ubuntu-latest
    needs: [testTKG]
    if: cancelled()
    steps:
    - name: Create comment
      uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          comment_body = `
          @${{ github.actor }} Build(s) cancelled, workflow Run ID: [${{ GITHUB.RUN_ID }}](${{ GITHUB.SERVER_URL }}/${{ GITHUB.REPOSITORY }}/actions/runs/${{ GITHUB.RUN_ID }})
          `;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment_body
          })

  reportSuccess:
    runs-on: ubuntu-latest
    needs: [testTKG]
    if: success()
    steps:
    - name: Create comment
      uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          comment_body = `
          @${{ github.actor }} Build(s) successful, workflow Run ID: [${{ GITHUB.RUN_ID }}](${{ GITHUB.SERVER_URL }}/${{ GITHUB.REPOSITORY }}/actions/runs/${{ GITHUB.RUN_ID }})
          `;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment_body
          })
